- hosts: localhost
  connection: local
  gather_facts: false 

  tasks: 
  - name: create key
    amazon.aws.ec2_key:
      name: test-key
      region: us-east-1
    register: key-info

  - ansible.builtin.debug:
      var: key-info

  - name: store private-key
    ansible.builtin.copy:
      content: {{ key-info.key.private_key }} 
      dest: ./test-key.pem

# make sure that you have boto
# sudo apt install pytho3-boto3 


########################
########################
########################

# - name: create a new EC2 key pair, returns generated private key
#   # use no_log to avoid private key being displayed into output
#   amazon.aws.ec2_key:
#     name: my_keypair
#   no_log: true
#   register: aws_ec2_key_pair

# - name: create key pair using provided key_material
#   amazon.aws.ec2_key:
#     name: my_keypair
#     key_material: 'ssh-rsa AAAAxyz...== me@example.com'

# - name: create key pair using key_material obtained using 'file' lookup plugin
#   amazon.aws.ec2_key:
#     name: my_keypair
#     key_material: "{{ lookup('file', '/path/to/public_key/id_rsa.pub') }}"

# - name: Create ED25519 key pair and save private key into a file
#   amazon.aws.ec2_key:
#     name: my_keypair
#     key_type: ed25519
#     file_name: /tmp/aws_ssh_rsa

# # try creating a key pair with the name of an already existing keypair
# # but don't overwrite it even if the key is different (force=false)
# - name: try creating a key pair with name of an already existing keypair
#   amazon.aws.ec2_key:
#     name: my_existing_keypair
#     key_material: 'ssh-rsa AAAAxyz...== me@example.com'
#     force: false

# - name: remove key pair from AWS by name
#   amazon.aws.ec2_key:
#     name: my_keypair
#     state: absent