- hosts: localhost
  connection: local
  gather_facts: false


  tasks: 
   - name: import vpc vars 
     ansible.builtin.include_vars: vars/vpc_setup


   - name: create vpc
     amazon.aws.ec2_vpc_net:
      name: "{{vpc_name}}"
      cidr_block: "{{vpc-cidr}}"
      region: {{region}}
      dns_support: yes
      dns_hostnames: yes
      tenancy: default
      state: "{{state}}" 
     register: vpc_out   


  #  - name: print output
  #    ansible.builtin.debug:
  #     var: vpc_out


   - name: create pub1 subnet in zone1
     amazon.aws.ec2_vpc_subnet:
       vpc_id: "{{vpc_out.vpc.id}}" 
       region: "{{region}}"
       az: "{{zone1}}"
       state: "{{state}}"  
       cidr: "{{pub-sub1}}"   
       map_public: yes
       resource_tags:
        name: vpro-pubsub1 
     register: pubsub1_out  

   - name: create pub2 subnet in zone2
     amazon.aws.ec2_vpc_subnet:
       vpc_id: "{{vpc_out.vpc.id}}" 
       region: "{{region}}"
       az: "{{zone2}}"
       state: "{{state}}"  
       cidr: "{{pub-sub2}}"   
       map_public: yes
       resource_tags:
        name: vpro-pubsub2 
     register: pubsub2_out  
   
   
   - name: create pub3 subnet in zone3
     amazon.aws.ec2_vpc_subnet:
       vpc_id: "{{vpc_out.vpc.id}}" 
       region: "{{region}}"
       az: "{{zone3}}"
       state: "{{state}}"  
       cidr: "{{pub-sub3}}"   
       map_public: yes
       resource_tags:
        name: vpro-pubsub3 
     register: pubsub3_out  
   
   
   - name: create priv1 subnet in zone1
     amazon.aws.ec2_vpc_subnet:
       vpc_id: "{{vpc_out.vpc.id}}" 
       region: "{{region}}"
       az: "{{zone1}}"
       state: "{{state}}"  
       cidr: "{{priv-sub1}}"   
       map_public: yes
       resource_tags:
        name: vpro-privsub1
     register: privsub1_out   
   
   
   - name: create priv2 subnet in zone2
     amazon.aws.ec2_vpc_subnet:
       vpc_id: "{{vpc_out.vpc.id}}" 
       region: "{{region}}"
       az: "{{zone2}}"
       state: "{{state}}"  
       cidr: "{{priv-sub2}}"   
       map_public: yes
       resource_tags:
        name: vpro-privsub2
     register: privsub2_out   
     
   - name: create priv3 subnet in zone3
     amazon.aws.ec2_vpc_subnet:
       vpc_id: "{{vpc_out.vpc.id}}" 
       region: "{{region}}"
       az: "{{zone3}}"
       state: "{{state}}"  
       cidr: "{{priv-sub3}}"   
       map_public: yes
       resource_tags:
        name: vpro-privsub3
     register: privsub3_out              
      
      


   - name: internet gateway 
     amazon.aws.ec2_vpc_igw: 
       vpc_id: "{{ vpc_out.vpc.id }}" 
       region: "{{region}}"
       state: "{{state}}" 
       resource_tags:
         name: vpro-IGW 
     register: IGW_out



   - name: route table for public subnets 
     amazon.aws.ec2_vpc_route_table:
       vpc_id: "{{ vpc_out.vpc.id }}" 
       region: "{{region}}"
       state: "{{state}}" 
       tags:
         name: vpro-IGW       
       subnets:
        - {{pubsub1_out.subnet.id}}
        - {{pubsub2_out.subnet.id}}
        - {{pubsub3_out.subnet.id}}
       routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{IGW_out.gateway_id}}"      
     register: pub_RT_out 
 

 ## now for private subnets create nat gateway and route table 


   - name: create nat gateway and allocate new elastic ip if nat gateway does't yet exist 
     amazon.aws.ec2_vpc_nat_gateway:
      state: "{{state}}" 
      subnet_id: "{{pubsub1_out.subnet.id}}"  # we will create only one nat gateway in one single pub subnet becuse it's not free 
      wait: yes
      region: "{{region}}"
      if_exist_do_not_create: yes
     register: NAT_GW_OUT
            
# now create RT for private subnets to route the traffic to nat gateway 

   - name: route table for private subnets 
     amazon.aws.ec2_vpc_route_table:
       vpc_id: "{{ vpc_out.vpc.id }}" 
       region: "{{region}}"
       tags:
         name: vpro-IGW       
       subnets:
        - {{privsub1_out.subnet.id}}
        - {{privsub2_out.subnet.id}}
        - {{privsub3_out.subnet.id}}
       routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{NAT_GW_out.gateway_id}}"      
     register: priv_RT_out 

########################
# we need to store var like id of subnet,vpc .into a file so we can reuse it later 


   - name: print vars
     ansible.builtin.debug:
      var: "{{ item }}"
     loop: 
        - vpc_out.vpc.id
        - privsub1_out.subnet.id
        - privsub2_out.subnet.id
        - privsub3_out.subnet.id         
        - pubsub1_out.subnet.id
        - pubsub2_out.subnet.id
        - pubsub3_out.subnet.id
        - NAT_GW_out.gateway_id
        - IGW_out.gateway_id 
        - priv_RT_out.route_table.id
        - pub_RT_out.route_table.id
        
   # we need to store them


   - name: store vars using set-fact
     ansible.builtin.set_fact:
      vpcid: "{{vpc_out.vpc.id}}"
      privsub1id: "{{privsub1_out.subnet.id}}"
      privsub2id: "{{privsub2_out.subnet.id}}"
      privsub3id: "{{privsub3_out.subnet.id}}"
      pubsub1id: "{{pubsub1_out.subnet.id}}"
      pubsub2id: "{{pubsub2_out.subnet.id}}"
      pubsub3id: "{{pubsub3_out.subnet.id}}"
      igwid:  "{{IGW_out.gateway_id }}"
      natgwid: "{{NAT_GW_out.gateway_id}}"
      pubRTid: "{{pub_RT_out.route_table.id}}"
      privRTid:  "{{priv_RT_out.route_table.id}}"
      cacheable: yes # to cache vars 


  # now store at file 

   - name: copy vars to file 
     ansible.builtin.copy:
      content: "  vpcid: {{vpc_out.vpc.id}} \n privsub1id: {{privsub1_out.subnet.id}} \n     privsub2id: {{privsub2_out.subnet.id}} \n privsub3id: {{privsub3_out.subnet.id}} \n pubsub1id: {{pubsub1_out.subnet.id}} \n  pubsub2id: {{pubsub2_out.subnet.id}} \n  pubsub3id: {{pubsub3_out.subnet.id}} \n  pubsub3id: {{pubsub3_out.subnet.id}} \n  natgwid: {{NAT_GW_out.gateway_id}} \n pubRTid: {{pub_RT_out.route_table.id}} \n privRTid:{{priv_RT_out.route_table.id}}"    
      dest: vars/output_vars

 ## ansible-playbook vpc-setup.yml 
########################
########PHASE ONE#########
##########################
