- hosts: localhost
  connection: local
  gather_facts: false


  tasks: 
   - name: import vpc vars 
     ansible.builtin.include_vars: vars/vpc_setup


   - name: create vpc
     amazon.aws.ec2_vpc_net:
      name: "{{vpc_name}}"
      cidr_block: "{{vpc-cidr}}"
      region: {{region}}
      dns_support: yes
      dns_hostnames: yes
      tenancy: default
      state: "{{state}}" 
     register: vpc_out   


  #  - name: print output
  #    ansible.builtin.debug:
  #     var: vpc_out


   - name: create pub1 subnet in zone1
     amazon.aws.ec2_vpc_subnet:
       vpc_id: "{{vpc_out.vpc.id}}" 
       region: "{{region}}"
       az: "{{zone1}}"
       state: "{{state}}"  
       cidr: "{{pub-sub1}}"   
       map_public: yes
       resource_tags:
        name: vpro-pubsub1 
     register: pubsub1_out  

   - name: create pub2 subnet in zone2
     amazon.aws.ec2_vpc_subnet:
       vpc_id: "{{vpc_out.vpc.id}}" 
       region: "{{region}}"
       az: "{{zone2}}"
       state: "{{state}}"  
       cidr: "{{pub-sub2}}"   
       map_public: yes
       resource_tags:
        name: vpro-pubsub2 
     register: pubsub2_out  
   
   
   - name: create pub3 subnet in zone3
     amazon.aws.ec2_vpc_subnet:
       vpc_id: "{{vpc_out.vpc.id}}" 
       region: "{{region}}"
       az: "{{zone3}}"
       state: "{{state}}"  
       cidr: "{{pub-sub3}}"   
       map_public: yes
       resource_tags:
        name: vpro-pubsub3 
     register: pubsub3_out  
   
   
   - name: create priv1 subnet in zone1
     amazon.aws.ec2_vpc_subnet:
       vpc_id: "{{vpc_out.vpc.id}}" 
       region: "{{region}}"
       az: "{{zone1}}"
       state: "{{state}}"  
       cidr: "{{priv-sub1}}"   
       map_public: yes
       resource_tags:
        name: vpro-privsub1
     register: privsub1_out   
   
   
   - name: create priv2 subnet in zone2
     amazon.aws.ec2_vpc_subnet:
       vpc_id: "{{vpc_out.vpc.id}}" 
       region: "{{region}}"
       az: "{{zone2}}"
       state: "{{state}}"  
       cidr: "{{priv-sub2}}"   
       map_public: yes
       resource_tags:
        name: vpro-privsub2
     register: privsub2_out   
     
   - name: create priv3 subnet in zone3
     amazon.aws.ec2_vpc_subnet:
       vpc_id: "{{vpc_out.vpc.id}}" 
       region: "{{region}}"
       az: "{{zone3}}"
       state: "{{state}}"  
       cidr: "{{priv-sub3}}"   
       map_public: yes
       resource_tags:
        name: vpro-privsub3
     register: privsub3_out              
      
      


   - name: internet gateway 
     amazon.aws.ec2_vpc_igw: 
       vpc_id: "{{ vpc_out.vpc.id }}" 
       region: "{{region}}"
       state: "{{state}}" 
       resource_tags:
         name: vpro-IGW 
     register: IGW_out
                     


        
          
     



 ## ansible-playbook vpc-setup.yml 
